package game.orders;

public enum OrderType {
   SHIP_MOVE,
   SHIP_SHOOT,
   SHIP_TAKE_SYSTEM,

   PLANET_UPGRADE,
   PLANET_DOWNGRADE,
   PLANET_BUILD_SHIP,

   FORTRESS_BUILD,
   FORTRESS_UPGRADE,
   FORTRESS_DOWNGRADE
}
